// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package autogen

import (
	"time"
)

type GroupDetailFilter struct {
	GroupID int `json:"groupId"`
}

type Mutation struct {
}

type NewGroupInput struct {
	OwnerID string    `json:"ownerId"`
	Remark  string    `json:"remark"`
	EndedAt time.Time `json:"endedAt"`
}

type NewUserInput struct {
	UserID   string `json:"userId"`
	Username string `json:"username"`
}

type Query struct {
}
