// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package autogen

import (
	"time"
)

type GroupDetailFilter struct {
	GroupID string  `json:"groupId"`
	OwnerID *string `json:"ownerId,omitempty"`
}

type Mutation struct {
}

type NewGroupInput struct {
	OwnerID  string            `json:"ownerId"`
	Remark   string            `json:"remark"`
	Products []NewProductInput `json:"products,omitempty"`
	EndedAt  time.Time         `json:"endedAt"`
}

type NewProductInput struct {
	Name  string `json:"name"`
	Price int    `json:"price"`
}

type Query struct {
}
